name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    strategy:
      matrix:
        node: ["16"]

    name: Documentation (Node v${{ matrix.node }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist-web
