name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: Leomotors/auto-publish-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_MUST_INCREASE: true
          RELEASE_TITLE: "Stupid Problems System {VERSION}"
          RELEASE_ON_KEYWORD: ${{ github.event.head_commit.message }}
          ALWAYS_GENERATE_NOTES: true
